In [9]:
import snscrape.modules.twitter as sntwitter
import pandas as pd



# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#Datascience since:2022-01-01 until:2022-06-25').get_items()):

    if i>500:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.url,\
                         tweet.user.username, tweet.user.followersCount,tweet.replyCount,\
                        tweet.retweetCount, tweet.likeCount, tweet.quoteCount, tweet.lang,\
                        tweet.outlinks, tweet.media, tweet.retweetedTweet, tweet.quotedTweet,\
                        tweet.inReplyToTweetId, tweet.inReplyToUser, tweet.mentionedUsers,\
                         tweet.coordinates, tweet.place, tweet.hashtags, tweet.cashtags])
# Creating a datafram from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'link', 'Username', 'followers', 'replies', 'retweets',
                                                'likes', 'qoutes', 'Lang', 'outlink', 'media', 'Retweeted tweets', 'Quoted tweet', 'inReplyToTweetId',
                                                'inReplyToUser', 'mentionedUsers', 'coordinates', 'place', 'hashtags', 'cashtags'])
tweets_df2

,Datetime,Tweet Id,Text,link,Username,followers,replies,retweets,likes,qoutes,...,media,Retweeted tweets,Quoted tweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,2022-06-24 23:58:57+00:00,1540484656465846272,OCaml Programming: Correct and Efficient and B...,https://twitter.com/GavLaaaaaaaa/status/154048...,GavLaaaaaaaa,8209,0,7,4,0,...,None,None,None,NaN,None,None,None,None,"[programming, softwareengineering, bigdata, da...",None
1,2022-06-24 23:58:02+00:00,1540484427121364992,Cheers for Nikhil. \n@analytics #MachineLearni...,https://twitter.com/unfoldds/status/1540484427...,unfoldds,175,1,2,3,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,[https://twitter.com/analytics],None,None,"[MachineLearning, DataScience, Python]",None
2,2022-06-24 23:57:49+00:00,1540484369340452865,Daily US Covid Deaths by County For IA 2022-...,https://twitter.com/njoyflyfishing/status/1540...,njoyflyfishing,87,0,2,2,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,None,None,None,"[datavisualization, datascience, analytics, he...",None
3,2022-06-24 23:56:21+00:00,1540484001793966081,"I love my job, I am passionate about @DataSciA...",https://twitter.com/lindamciver/status/1540484...,lindamciver,3403,0,7,15,0,...,None,None,None,NaN,None,"[https://twitter.com/DataSciAu, https://twitte...",None,None,"[datascience, stem]",None
4,2022-06-24 23:55:27+00:00,1540483775972331520,Daily US Covid Deaths by County For IN 2022-...,https://twitter.com/njoyflyfishing/status/1540...,njoyflyfishing,87,0,2,1,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,None,None,None,"[datavisualization, datascience, analytics, he...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,2022-06-24 17:45:28+00:00,1540390667586871301,Data Normalization in R \nData Normalization i...,https://twitter.com/DataSciencetut/status/1540...,DataSciencetut,1405,0,1,2,0,...,None,None,None,NaN,None,None,None,None,"[rstudio, rstats, tidyverse, programming, data...",None
497,2022-06-24 17:45:16+00:00,1540390616332267520,Daily US Confirmed Covid Cases by County For N...,https://twitter.com/njoyflyfishing/status/1540...,njoyflyfishing,87,0,1,1,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,None,None,None,"[datavisualization, datascience, analytics, he...",None
498,2022-06-24 17:43:20+00:00,1540390127729446917,Daily US Confirmed Covid Cases by County For N...,https://twitter.com/njoyflyfishing/status/1540...,njoyflyfishing,87,0,1,1,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,None,None,None,"[datavisualization, datascience, analytics, he...",None
499,2022-06-24 17:43:19+00:00,1540390125246578688,Hex Brings Flexible Analytics &amp; Data Scien...,https://twitter.com/Neurons_AI/status/15403901...,Neurons_AI,3242,0,0,0,0,...,None,None,None,NaN,None,None,None,None,"[datascience, intoAInews]",None
500,2022-06-24 17:43:02+00:00,1540390053544861697,😎 Spirax Sarco is hiring! Looking for a new Au...,https://twitter.com/WorkWithAIML/status/154039...,WorkWithAIML,30,0,0,0,0,...,[Photo(previewUrl='https://pbs.twimg.com/media...,None,None,NaN,None,None,None,None,"[DataScience, DataJobs]",None

In [8]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Creating list to append tweet data to
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:@SafaricomPlc since:2022-04-30 until:2022-06-01').get_items()):
    if i>5000:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.url,\
                         tweet.user.username, tweet.user.followersCount, tweet.replyCount,\
                        tweet.retweetCount, tweet.likeCount, tweet.quoteCount, tweet.lang,\
                        tweet.outlinks, tweet.media, tweet.retweetedTweet, tweet.quotedTweet,\
                        tweet.inReplyToTweetId, tweet.inReplyToUser, tweet.mentionedUsers,\
                         tweet.coordinates, tweet.place, tweet.hashtags, tweet.cashtags])
    
# Creating a dataframe from the tweets list above 
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'link', 'Username', 'followers', 'replies', 'retweets',
                                                'likes', 'qoutes', 'Lang', 'outlink', 'media', 'Retweeted tweets', 'Quoted tweet', 'inReplyToTweetId',
                                                'inReplyToUser', 'mentionedUsers', 'coordinates', 'place', 'hashtags', 'cashtags'])
tweets_df1

,Datetime,Tweet Id,Text,link,Username,followers,replies,retweets,likes,qoutes,...,media,Retweeted tweets,Quoted tweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,2022-05-31 23:06:38+00:00,1531774183058944000,@suleHajji50 @suleHajji50 : You can try opt o...,https://twitter.com/SafaricomPLC/status/153177...,SafaricomPLC,1756201,0,0,0,0,...,None,None,None,1.531766e+18,https://twitter.com/suleHajji50,"[https://twitter.com/suleHajji50, https://twit...",None,None,None,None
1,2022-05-31 22:42:47+00:00,1531768178459697153,@Adanmaalim8 Sorry Adan. Recipient has actuall...,https://twitter.com/SafaricomPLC/status/153176...,SafaricomPLC,1756201,0,0,0,0,...,None,None,None,1.531758e+18,https://twitter.com/Adanmaalim8,[https://twitter.com/Adanmaalim8],None,None,None,None
2,2022-05-31 22:27:02+00:00,1531764217581297664,@nyawanx @nyawanx : Sorry about that but how ...,https://twitter.com/SafaricomPLC/status/153176...,SafaricomPLC,1756201,0,0,0,0,...,None,None,None,1.531754e+18,https://twitter.com/nyawanx,"[https://twitter.com/nyawanx, https://twitter....",None,None,None,None
3,2022-05-31 21:31:35+00:00,1531750259877105664,"@onyango988 @onyango988 : Hi Onyango, kindly s...",https://twitter.com/SafaricomPLC/status/153175...,SafaricomPLC,1756201,1,0,1,0,...,None,None,None,1.531738e+18,https://twitter.com/onyango988,"[https://twitter.com/onyango988, https://twitt...",None,None,None,None
4,2022-05-31 20:55:15+00:00,1531741116260827137,@SirmeMtalii Hello Sirme. Kindly DM your numbe...,https://twitter.com/SafaricomPLC/status/153174...,SafaricomPLC,1756201,0,0,1,0,...,None,None,None,1.531728e+18,https://twitter.com/SirmeMtalii,[https://twitter.com/SirmeMtalii],None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2596,2022-04-30 06:00:33+00:00,1520281934659739648,"@Jedigerald @Jedigerald : Hello, The transacti...",https://twitter.com/SafaricomPLC/status/152028...,SafaricomPLC,1756202,0,0,0,0,...,None,None,None,1.520281e+18,https://twitter.com/Jedigerald,"[https://twitter.com/Jedigerald, https://twitt...",None,None,None,None
2597,2022-04-30 05:45:24+00:00,1520278120561061888,"@artmugoh @artmugoh : Hi Artmugoh, DM https://...",https://twitter.com/SafaricomPLC/status/152027...,SafaricomPLC,1756202,0,0,0,0,...,None,None,None,1.520276e+18,https://twitter.com/artmugoh,"[https://twitter.com/artmugoh, https://twitter...",None,None,None,None
2598,2022-04-30 05:26:56+00:00,1520273475180576769,@MelowMelow254 @MelowMelow254 Hello Melow. Apo...,https://twitter.com/SafaricomPLC/status/152027...,SafaricomPLC,1756202,2,0,2,0,...,None,None,None,1.520272e+18,https://twitter.com/MelowMelow254,"[https://twitter.com/MelowMelow254, https://tw...",None,None,None,None
2599,2022-04-30 05:25:17+00:00,1520273059760029697,"@mu_kalee @mu_kalee : Jambo, we already respon...",https://twitter.com/SafaricomPLC/status/152027...,SafaricomPLC,1756202,1,0,0,0,...,None,None,None,1.520272e+18,https://twitter.com/mu_kalee,"[https://twitter.com/mu_kalee, https://twitter...",None,None,None,None
2600,2022-04-30 05:19:24+00:00,1520271581586632705,Junior golfer John Kitaka has been playing gol...,https://twitter.com/SafaricomPLC/status/152027...,SafaricomPLC,1756202,1,2,7,0,...,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,None,None,NaN,None,None,None,None,"[SafaricomGolfTour, EveryShotIsAnOpportunity]",None

In [5]:
#SEPARATE DATE AND TIME
import datetime as dt
tweets_df1['Date']=pd.to_datetime(tweets_df1['Datetime']).dt.date
tweets_df1['time']=pd.to_datetime(tweets_df1['Datetime']).dt.time
tweets_df1

,Datetime,Tweet Id,Text,link,Username,followers,replies,retweets,likes,qoutes,...,Quoted tweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,Date,time
0,2022-05-29 10:25:37+00:00,1530857888880771072,@engineers_feed 10,https://twitter.com/edwin__kanja/status/153085...,edwin__kanja,1151,0,0,0,0,...,None,1530783116956094464,https://twitter.com/engineers_feed,[https://twitter.com/engineers_feed],None,None,None,None,2022-05-29,10:25:37
1,2022-05-22 12:34:28+00:00,1528353601101389824,@chrissyacoder https://t.co/iQsgwOUKWF,https://twitter.com/edwin__kanja/status/152835...,edwin__kanja,1151,0,0,1,0,...,None,1527975867489652736,https://twitter.com/chrissyacoder,[https://twitter.com/chrissyacoder],None,None,None,None,2022-05-22,12:34:28
2,2022-05-18 10:52:23+00:00,1526878357320830984,@engineers_feed 420,https://twitter.com/edwin__kanja/status/152687...,edwin__kanja,1151,0,0,0,0,...,None,1526779710910345217,https://twitter.com/engineers_feed,[https://twitter.com/engineers_feed],None,None,None,None,2022-05-18,10:52:23

In [6]:
#TO CSV FORMAT
tweets_df1.to_csv('SafTweets.csv')